# Generated by Django 4.0.6 on 2022-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0002_auto_20220108_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpassword',
            name='salt',
            field=models.BinaryField(default=b'\x04\x87\x0c\x99?a\x81\xe1\x04R_k\xea\x90(nf\x1a}\xaf^p\xdb\xbf\xd8\xfdS\xb1\x8e\x93z~'),
        ),
    ]
