# Generated by Django 4.0.6 on 2022-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0004_alter_masterpassword_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpassword',
            name='salt',
            field=models.BinaryField(
                default=b'\x05\x14\xb89D\xa5\xf0\x86\x91\x16\xcc\x8c\xfd\xfb\xf8#X\xcd\xae\xca\x10\x90\xd5"\x0b\xb5\r\xa3\xa0\xa5g\x05'
            ),
        ),
    ]
