# Generated by Django 4.0.6 on 2022-08-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0006_alter_masterpassword_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpassword',
            name='salt',
            field=models.BinaryField(
                default=b'\xd8\x1arbMkFF\x1b\xc6M\xd3\xa3q\xfb\x93\xe7\xd5p&\x9a\x9daG4\xe9\x8d\xf2\xc3\xed\xd9\xe3'
            ),
        ),
    ]
