# Generated by Django 4.0.6 on 2022-08-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0008_alter_masterpassword_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpassword',
            name='salt',
            field=models.BinaryField(
                default=b'6r>`c\xa7\x95\x18\xa3\x8a\x81\x9b\xd9\xe9E\xfd=\x85bZ)\xa8\xa3l\xa4I\x19\x9c/$Y\x9d'
            ),
        ),
    ]
