<template>
  <div class="container">
    <div class="content settingscontainer">
      <div class="title">
        <h4>Algorithm Used</h4>
        <p>
          The current version of this password manager uses Advanced Encryption
          with Scrypt Algorithm.
        </p>
        <h4>Data Storage</h4>
        <p>
          This app does not store any information about your master password,
          not even a hashed version of it.
        </p>
        <h4>
          How the app determines whether your master password is correct or not?
        </h4>
        <p>
          It is simple, if the wrong password is given, it will fail to decrypt
          your entries and the algorithm will raise an "InvalidToken" error.
        </p>
        <h4>First Authentication</h4>
        <p>
          When you define a your new master password for the first time, a very
          random and unpredictable password is autogenerated. So the first time
          you login to your vault, the app does the verification on that random
          generated password.
        </p>
        <p>
          This proves to be a better alternative than storing an one way
          encrypted (hashed) version of users password, which would be easier to
          bruteforce.
        </p>
        <h4>Generated Passwords</h4>
        <p>
          Generated passwords are long, strong, and completely random. The are
          based on umpredictable real words events. not writen preditermined
          algorithms.
        </p>
        <h4>Always choose a strong password</h4>
        <p>
          Computers are able to generate from thousands to billions of password
          guesses depending on algorithm used to encrypt or hash passwords. So,
          lowercase only and short passwords are very vulnerable to bruteforce.
          Always choose passwords longer than 10 chars (bare minimum) and
          include symbols and numbers, and lowercase and uppercase letters.
        </p>
      </div>
    </div>
  </div>
</template>
