# Generated by Django 3.0 on 2022-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0002_entry_is_generated_for_initial_master_pw_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpassword',
            name='master',
        ),
        migrations.AddField(
            model_name='masterpassword',
            name='has_defined_a_master_password',
            field=models.BooleanField(default=False),
        ),
    ]
